### ISSUE TITLE
reproduce the results

### ISSUE THREAD

**Issue by kaigelee** [aswahd/SamRadiology#1]
What kind of hardware can reproduce the results? For example, 1*3090?

**Comment by aswahd** [comment]
Hi @kaigelee,
I’m using an A100 GPU, but many of the models are <40M parameters and I believe a single 3090 should also work. I’m currently writing a README for a quick start guide, so keep an eye out for that!

**Comment by kaigelee** [comment]
Thank you for your reply. 
I would like to know whether your method is applicable to the detection of multiple objects in one image?
If not, how can I modify the code?

**Comment by aswahd** [comment]
@kaigelee
Yes. 

If it is semantic segmentation, you simply need to specify the number of classes in your config.

Example: Semantic Segmentation: [ACDC dataset](https://drive.google.com/drive/folders/14WIOWTF1WWwMaHV7UVo5rjWujpUxGetJ?usp=sharing).

```yaml
image_size: 1024
image_encoder: "sam2_tiny_hiera_adapter"
mask_decoder: "sam2_lora_mask_decoder"
sam_checkpoint: "weights/sam2_hiera_tiny.pt"
wandb_project_name: "ACDC"

dataset:
  name: acdc
  root: /path/to/your/dataset
  image_size: 1024
  num_classes: 3
  num_tokens: 10

training:
  max_epochs: 200
  save_path: checkpoints/ACDC

```

If you’re doing instance segmentation, while prompt learning works well, you’ll need a bipartite matching loss similar to [DETR](https://github.com/facebookresearch/detr).


Hope it helps!
